import re

def extract_species(reactants, products):
    species = set()
    # Combine both blocks
    all_lines = (reactants + "\n" + products).splitlines()
    for line in all_lines:
        line = line.strip()
        if not line or line == "[]":
            continue
        # Split on '+'
        parts = line.split('+')
        for p in parts:
            p = p.strip()
            if not p or p == "[]":
                continue
            # Remove stoichiometric coefficients like '2*'
            p = re.sub(r'^\d+\*', '', p)
            species.add(p)
    return species

reactants = '''
EGF+EGFR
2*EGFR-EGF
EGFR-EGF-2
2*Her2
Her2-2
EGFR-EGF-2-p+Grb2
EGFR-EGF-2-p-Grb2+Sos
EGFR-EGF-2-p-Grb2-Sos
Grb2+Sos
EGFR-EGF-2-p-Grb2-Sos+Ras-GDP
EGFR-EGF-2-p-Grb2-Sos-Ras-GDP
Her2-2-p+Grb2
Her2-2-p-Grb2+Sos
Her2-2-p-Grb2-Sos
Her2-2-p-Grb2-Sos+Ras-GDP
Her2-2-p-Grb2-Sos-Ras-GDP
EGFR-EGF-2-p+Shc
EGFR-EGF-2-p-Shc
EGFR-EGF-2-p-Shc-p
Shc-p
EGFR-EGF-2-p-Shc-p+Grb2
EGFR-EGF-2-p-Shc-p-Grb2+Sos
EGFR-EGF-2-p-Shc-p-Grb2-Sos
Shc-p+Grb2-Sos
EGFR-EGF-2-p-Shc-p-Grb2-Sos+Ras-GDP
EGFR-EGF-2-p-Shc-p-Grb2-Sos-Ras-GDP
Her2-2-p+Shc
Her2-2-p-Shc
Her2-2-p-Shc-p
Her2-2-p-Shc-p+Grb2
Her2-2-p-Shc-p-Grb2+Sos
Her2-2-p-Shc-p-Grb2-Sos
Her2-2-p-Shc-p-Grb2-Sos+Ras-GDP
Her2-2-p-Shc-p-Grb2-Sos-Ras-GDP
Her2-2-p+cPAcP
Her2-2-p-cPAcP
Her2-2+sPAcP
Her2-2-sPAcP
Ras-GTP+GAP
Ras-GTP-GAP
Ras-GTP+Raf
Ras-GTP-Raf
Raf-p+Pase1
Raf-p-Pase1
MEK+Raf-p
MEK-Raf-p
MEK-p+Raf-p
MEK-p-Raf-p
ERK+MEK-pp
ERK-MEK-pp
ERK-p+MEK-pp
ERK-p-MEK-pp
MEK-p+Pase2
MEK-p-Pase2
MEK-pp+Pase2
MEK-pp-Pase2
ERK-p+Pase3
ERK-p-Pase3
ERK-pp+Pase3
ERK-pp-Pase3
EGFR-EGF-2-p-Grb2-Sos+ERK-pp
EGFR-EGF-2-p-Grb2-Sos-ERK-pp
Her2-2-p-Grb2-Sos+ERK-pp
Her2-2-p-Grb2-Sos-ERK-pp
EGFR-EGF-2-p-Shc-p-Grb2-Sos+ERK-pp
EGFR-EGF-2-p-Shc-p-Grb2-Sos-ERK-pp
Her2-2-p-Shc-p-Grb2-Sos+ERK-pp
Her2-2-p-Shc-p-Grb2-Sos-ERK-pp
EGF
EGFR
EGFR-EGF
EGFRi+EGFi
EGFR-EGF-2
2*EGFR-EGFi
EGFR-EGF-2-p
EGFR-EGF-2i
EGFR-EGF-2-p-Grb2
EGFR-EGF-2-pi+Grb2
EGFR-EGF-2-p-Grb2-Sos
EGFR-EGF-2-pi+Grb2-Sos
EGFR-EGF-2-pi-Grb2+Sos
EGFR-EGF-2-pi-Grb2-Sos+Ras-GDP
EGFR-EGF-2-pi-Grb2-Sos-Ras-GDP
EGFR-EGF-2-pi-Grb2-Sos+ERK-pp
EGFR-EGF-2-pi-Grb2-Sos-ERK-pp
EGFR-EGF-2-pi+Shc
EGFR-EGF-2-p-Shc
EGFR-EGF-2-pi-Shc
EGFR-EGF-2-p-Shc-p
EGFR-EGF-2-pi-Shc-p
EGFR-EGF-2-pi-Shc-p+Grb2
EGFR-EGF-2-p-Shc-p-Grb2
EGFR-EGF-2-pi-Shc-p-Grb2+Sos
EGFR-EGF-2-p-Shc-p-Grb2-Sos
EGFR-EGF-2-pi-Shc-p-Grb2-Sos
EGFR-EGF-2-pi-Shc-p-Grb2-Sos+Ras-GDP
EGFR-EGF-2-pi-Shc-p-Grb2-Sos-Ras-GDP
EGFR-EGF-2-pi-Shc-p-Grb2-Sos+ERK-pp
EGFR-EGF-2-pi-Shc-p-Grb2-Sos-ERK-pp
AR+ERK-pp
AR-ERK-pp
T+Rase5a
T-Rase5a
AR+HSP
AR+T
AR-T
AR-p+AR-p-T
2*AR-p-T
2*AR-p
AR+DHT
AR-DHT
AR-p-DHT+AR-p-T
AR-p-DHT+AR-p
2*AR-p-DHT
AR-p+Pase5
AR-p-Pase5
AR-p-T+Pase5
AR-p-T-Pase5
AR-p-DHT+Pase5
AR-p-DHT-Pase5
AR-p-2+g-cPAcP
AR-p-DHT-2+g-cPAcP
AR-p-DHT-AR-p+g-cPAcP
AR-p-T-2+g-cPAcP
AR-p-AR-p-T+g-cPAcP
AR-p-DHT-AR-p-T+g-cPAcP
AR-p-2+g-sPAcP
AR-p-DHT-2+g-sPAcP
AR-p-DHT-AR-p+g-sPAcP
AR-p-T-2+g-sPAcP
AR-p-AR-p-T+g-sPAcP
AR-p-DHT-AR-p-T+g-sPAcP
ERK-pp+ETS
ERK-pp-ETS
ETS-p+Pase5
ETS-p-Pase5
ERK-pp+AP1
ERK-pp-AP1
AP1-p+Pase6
AP1-p-Pase6
Her2-2-p-Grb2-Sos+PI3K
Her2-2-p-Grb2-Sos-PI3K
Her2-2-p-Shc-p-Grb2-Sos+PI3K
Her2-2-p-Shc-p-Grb2-Sos-PI3K
EGFR-EGF-2-p-Grb2-Sos+PI3K
EGFR-EGF-2-p-Grb2-Sos-PI3K
EGFR-EGF-2-p-Shc-p-Grb2-Sos+PI3K
EGFR-EGF-2-p-Shc-p-Grb2-Sos-PI3K
PtdIns2+Act-PI3K
PtdIns2-Act-PI3K
PtdIns3+PTEN
PtdIns3-PTEN
PtdIns3+Akt
PtdIns3-Akt
PtdIns3+Pdk1
PtdIns3-Pdk1
Pdk1-m+Akt-m
Pdk1-m-Akt-m
Act-Akt+TOR
Act-Akt-TOR
4E-BP1+eIF4E
4E-BP1+Act-TOR
4E-BP1-Act-TOR
T-e
sPAcP
g-CycD+RNAp
g-CycD-RNAp
g-CycD+ETS-p
g-CycD-ETS-p+RNAp
g-CycD-ETS-p-RNAp
g-CycD+AP1-p
g-CycD-AP1-p+RNAp
g-CycD-AP1-p-RNAp
g-PSA+RNAp
g-PSA-RNAp
g-PSA+AR-p-2
g-PSA-AR-p-2+RNAp
g-PSA-AR-p-2-RNAp
g-PSA+AR-p-DHT-2
g-PSA-AR-p-DHT-2+RNAp
g-PSA-AR-p-DHT-2-RNAp
g-PSA+AR-p-DHT-AR-p
g-PSA-AR-p-DHT-AR-p+RNAp
g-PSA-AR-p-DHT-AR-p-RNAp
g-PSA+AR-p-T-2
g-PSA-AR-p-T-2+RNAp
g-PSA-AR-p-T-2-RNAp
g-PSA+AR-p-AR-p-T
g-PSA-AR-p-AR-p-T+RNAp
g-PSA-AR-p-AR-p-T-RNAp
g-PSA+AR-p-DHT-AR-p-T
g-PSA-AR-p-DHT-AR-p-T+RNAp
g-PSA-AR-p-DHT-AR-p-T-RNAp
g-cPAcP+RNAp
g-cPAcP-RNAp
g-sPAcP+RNAp
g-sPAcP-RNAp
mRNA-CycD+eIF4E
mRNA-CycD-eIF4E+40S
mRNA-CycD-eIF4E-40S+60S
mRNA-CycD-eIF4E-40S-60S
Rm-CycD
Ar-CycD
mRNA-PSA+eIF4E
mRNA-PSA-eIF4E+40S
mRNA-PSA-eIF4E-40S+60S
mRNA-PSA-eIF4E-40S-60S
Rm-PSA
Ar-PSA
mRNA-cPAcP+eIF4E
mRNA-cPAcP-eIF4E+40S
mRNA-cPAcP-eIF4E-40S+60S
mRNA-cPAcP-eIF4E-40S-60S
Rm-cPAcP
Ar-cPAcP
mRNA-sPAcP+eIF4E
mRNA-sPAcP-eIF4E+40S
mRNA-sPAcP-eIF4E-40S+60S
mRNA-sPAcP-eIF4E-40S-60S
Rm-sPAcP
Ar-sPAcP
mRNA-CycD
mRNA-PSA
CycD
PSA
EGFi
cPAcP
mRNA-cPAcP
sPAcP
mRNA-sPAcP
2*cPAcP
2*cPAcP-2
2*Her2-2-p+cPAcP-2
2Her2-2-p-cPAcP-2
4*Her2-2-p+cPAcP-4
4Her2-2-p-cPAcP-4
Act-Akt+Pase7
Act-Akt-Pase7
4E-BP1-eIF4E+Act-TOR
4E-BP1-eIF4E-Act-TOR
'''

products = '''
EGFR-EGF
EGFR-EGF-2
EGFR-EGF-2-p
Her2-2
Her2-2-p
EGFR-EGF-2-p-Grb2
EGFR-EGF-2-p-Grb2-Sos
EGFR-EGF-2-p+Grb2-Sos
Grb2-Sos
EGFR-EGF-2-p-Grb2-Sos-Ras-GDP
EGFR-EGF-2-p-Grb2-Sos+Ras-GTP
Her2-2-p-Grb2
Her2-2-p-Grb2-Sos
Her2-2-p+Grb2-Sos
Her2-2-p-Grb2-Sos-Ras-GDP
Her2-2-p-Grb2-Sos+Ras-GTP
EGFR-EGF-2-p-Shc
EGFR-EGF-2-p-Shc-p
EGFR-EGF-2-p+Shc-p
Shc
EGFR-EGF-2-p-Shc-p-Grb2
EGFR-EGF-2-p-Shc-p-Grb2-Sos
EGFR-EGF-2-p+Shc-p-Grb2-Sos
Shc-p-Grb2-Sos
EGFR-EGF-2-p-Shc-p-Grb2-Sos-Ras-GDP
EGFR-EGF-2-p-Shc-p-Grb2-Sos+Ras-GTP
Her2-2-p-Shc
Her2-2-p-Shc-p
Her2-2-p+Shc-p
Her2-2-p-Shc-p-Grb2
Her2-2-p-Shc-p-Grb2-Sos
Her2-2-p+Shc-p-Grb2-Sos
Her2-2-p-Shc-p-Grb2-Sos-Ras-GDP
Her2-2-p-Shc-p-Grb2-Sos+Ras-GTP
Her2-2-p-cPAcP
Her2-2+cPAcP
Her2-2-sPAcP
Her2-2-p+sPAcP
Ras-GTP-GAP
Ras-GDP+GAP
Ras-GTP-Raf
Ras-GTP+Raf-p
Raf-p-Pase1
Raf+Pase1
MEK-Raf-p
MEK-p+Raf-p
MEK-p-Raf-p
MEK-pp+Raf-p
ERK-MEK-pp
ERK-p+MEK-pp
ERK-p-MEK-pp
ERK-pp+MEK-pp
MEK-p-Pase2
MEK+Pase2
MEK-pp-Pase2
MEK-p+Pase2
ERK-p-Pase3
ERK+Pase3
ERK-pp-Pase3
ERK-p+Pase3
EGFR-EGF-2-p-Grb2-Sos-ERK-pp
EGFR-EGF-2-p-Grb2+Sos+ERK-pp
Her2-2-p-Grb2-Sos-ERK-pp
Her2-2-p-Grb2+Sos+ERK-pp
EGFR-EGF-2-p-Shc-p-Grb2-Sos-ERK-pp
EGFR-EGF-2-p-Shc-p-Grb2+Sos+ERK-pp
Her2-2-p-Shc-p-Grb2-Sos-ERK-pp
Her2-2-p-Shc-p-Grb2+Sos+ERK-pp
EGFi
EGFRi
EGFR-EGFi
EGFR-EGFi
EGFR-EGF-2i
EGFR-EGF-2i
EGFR-EGF-2-pi
EGFR-EGF-2-pi
EGFR-EGF-2-pi-Grb2
EGFR-EGF-2-pi-Grb2
EGFR-EGF-2-pi-Grb2-Sos
EGFR-EGF-2-pi-Grb2-Sos
EGFR-EGF-2-pi-Grb2-Sos
EGFR-EGF-2-pi-Grb2-Sos-Ras-GDP
EGFR-EGF-2-pi-Grb2-Sos+Ras-GTP
EGFR-EGF-2-pi-Grb2-Sos-ERK-pp
EGFR-EGF-2-pi-Grb2+Sos+ERK-pp
EGFR-EGF-2-pi-Shc
EGFR-EGF-2-pi-Shc
EGFR-EGF-2-pi-Shc-p
EGFR-EGF-2-pi-Shc-p
EGFR-EGF-2-pi+Shc-p
EGFR-EGF-2-pi-Shc-p-Grb2
EGFR-EGF-2-pi-Shc-p-Grb2
EGFR-EGF-2-pi-Shc-p-Grb2-Sos
EGFR-EGF-2-pi-Shc-p-Grb2-Sos
EGFR-EGF-2-pi+Shc-p-Grb2-Sos
EGFR-EGF-2-pi-Shc-p-Grb2-Sos-Ras-GDP
EGFR-EGF-2-pi-Shc-p-Grb2-Sos+Ras-GTP
EGFR-EGF-2-pi-Shc-p-Grb2-Sos-ERK-pp
EGFR-EGF-2-pi-Shc-p-Grb2+Sos+ERK-pp
AR-ERK-pp
AR-p+ERK-pp
T-Rase5a
DHT+Rase5a
AR-HSP
AR-T
AR-p-T
AR-p-AR-p-T
AR-p-T-2
AR-p-2
AR-DHT
AR-p-DHT
AR-p-DHT-AR-p-T
AR-p-DHT-AR-p
AR-p-DHT-2
AR-p-Pase5
AR+Pase5
AR-p-T-Pase5
AR-T+Pase5
AR-p-DHT-Pase5
AR-DHT+Pase5
AR-p-2-g-cPAcP
AR-p-DHT-2-g-cPAcP
AR-p-DHT-AR-p-g-cPAcP
AR-p-T-2-g-cPAcP
AR-p-AR-p-T-g-cPAcP
AR-p-DHT-AR-p-T-g-cPAcP
AR-p-2-g-sPAcP
AR-p-DHT-2-g-sPAcP
AR-p-DHT-AR-p-g-sPAcP
AR-p-T-2-g-sPAcP
AR-p-AR-p-T-g-sPAcP
AR-p-DHT-AR-p-T-g-sPAcP
ERK-pp-ETS
ERK-pp+ETS-p
ETS-p-Pase5
ETS+Pase5
ERK-pp-AP1
ERK-pp+AP1-p
AP1-p-Pase6
AP1+Pase6
Her2-2-p-Grb2-Sos-PI3K
Her2-2-p-Grb2-Sos+Act-PI3K
Her2-2-p-Shc-p-Grb2-Sos-PI3K
Her2-2-p-Shc-p-Grb2-Sos+Act-PI3K
EGFR-EGF-2-p-Grb2-Sos-PI3K
EGFR-EGF-2-p-Grb2-Sos+Act-PI3K
EGFR-EGF-2-p-Shc-p-Grb2-Sos-PI3K
EGFR-EGF-2-p-Shc-p-Grb2-Sos+Act-PI3K
PtdIns2-Act-PI3K
PtdIns3+Act-PI3K
PtdIns3-PTEN
PtdIns2+PTEN
PtdIns3-Akt
PtdIns3+Akt-m
PtdIns3-Pdk1
PtdIns3+Pdk1-m
Pdk1-m-Akt-m
Pdk1+Act-Akt
Act-Akt-TOR
Akt+Act-TOR
4E-BP1-eIF4E
4E-BP1-Act-TOR
4E-BP1-P+Act-TOR
T
sPAcP-e
g-CycD-RNAp
g-CycD+RNAp+mRNA-CycD
g-CycD-ETS-p
g-CycD-ETS-p-RNAp
g-CycD-ETS-p+RNAp+mRNA-CycD
g-CycD-AP1-p
g-CycD-AP1-p-RNAp
g-CycD-AP1-p+RNAp+mRNA-CycD
g-PSA-RNAp
g-PSA+RNAp+mRNA-PSA
g-PSA-AR-p-2
g-PSA-AR-p-2-RNAp
g-PSA-AR-p-2+RNAp+mRNA-PSA
g-PSA-AR-p-DHT-2
g-PSA-AR-p-DHT-2-RNAp
g-PSA-AR-p-DHT-2+RNAp+mRNA-PSA
g-PSA-AR-p-DHT-AR-p
g-PSA-AR-p-DHT-AR-p-RNAp
g-PSA-AR-p-DHT-AR-p+RNAp+mRNA-PSA
g-PSA-AR-p-T-2
g-PSA-AR-p-T-2-RNAp
g-PSA-AR-p-T-2+RNAp+mRNA-PSA
g-PSA-AR-p-AR-p-T
g-PSA-AR-p-AR-p-T-RNAp
g-PSA-AR-p-AR-p-T+RNAp+mRNA-PSA
g-PSA-AR-p-DHT-AR-p-T
g-PSA-AR-p-DHT-AR-p-T-RNAp
g-PSA-AR-p-DHT-AR-p-T+RNAp+mRNA-PSA
g-cPAcP-RNAp
g-cPAcP+RNAp+mRNA-cPAcP
g-sPAcP-RNAp
g-sPAcP+RNAp+mRNA-sPAcP
mRNA-CycD-eIF4E
mRNA-CycD-eIF4E-40S
mRNA-CycD-eIF4E-40S-60S
Rm-CycD+eIF4E
Ar-CycD
CycD+40S+60S+mRNA-CycD
mRNA-PSA-eIF4E
mRNA-PSA-eIF4E-40S
mRNA-PSA-eIF4E-40S-60S
Rm-PSA+eIF4E
Ar-PSA
PSA+40S+60S+mRNA-PSA
mRNA-cPAcP-eIF4E
mRNA-cPAcP-eIF4E-40S
mRNA-cPAcP-eIF4E-40S-60S
Rm-cPAcP+eIF4E
Ar-cPAcP
cPAcP+40S+60S+mRNA-cPAcP
mRNA-sPAcP-eIF4E
mRNA-sPAcP-eIF4E-40S
mRNA-sPAcP-eIF4E-40S-60S
Rm-sPAcP+eIF4E
Ar-sPAcP
sPAcP+40S+60S+mRNA-sPAcP
[]
[]
[]
[]
[]
[]
[]
[]
[]
cPAcP-2
cPAcP-4
2Her2-2-p-cPAcP-2
2*Her2-2+cPAcP-2
4Her2-2-p-cPAcP-4
4*Her2-2+cPAcP-4
Act-Akt-Pase7
Akt+Pase7
4E-BP1-eIF4E-Act-TOR
4E-BP1-P+eIF4E+Act-TOR
'''

unique_species = extract_species(reactants, products)

for sp in sorted(unique_species):
    print(sp)
print()
print('Number of species:', len(unique_species))

